# Generated by Django 3.1.3 on 2020-11-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201121_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
