# Generated by Django 3.1.3 on 2020-11-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201121_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
